### ISSUE TITLE
Transitioning from insert mode to editor normal mode without losing cursor focus? [Question]

### ISSUE THREAD

**Issue by Positron010** [pit-ray/win-vind#26]
**Question**

Currently, switching from **insert mode** to **editor normal mode** causes the text field to lose focus, requiring clicking on the field to activate the text cursor again which is inconvenient. Is it possible to make the switch without the editor losing focus?

Thanks

**Comment by pit-ray** [comment]
Hi

There is nothing in win-vind to make the transition from **Insert Mode** to **Editor Normal Mode** lose focus of text field. What application's text field are you targeting? Perhaps the same keystroke as `to_edi_normal` will lose focus without win-vind? In that case, I recommend you change the bindings of `to_edi_normal`.

Thanks again

**Comment by Positron010** [comment]
Hi,

This happens even when using the default shortcut (esc+right). I'm not sure if it happens everywhere, but it do happen in multiple instances, even in this comment field.

Thanks.

**Comment by pit-ray** [comment]
Sorry for my late reply.

I tried but could not reproduce the phenomenon. Can you give me the details of .vindrc and the name of your browser?

Thanks.

**Comment by Positron010** [comment]
No problem.

I use the Microsoft Edge (Chromium based) browser.

Here is my .vindrc:

```
set vscroll_speed = 100
set hscroll_speed = 100
set cmd_fontname = monaco
set shell = cmd
set easyclick_fontsize = 24
set easyclick_fontname = CalendasPlus
set autotrack_popup
set cmd_roughpos = LowerLeft


gnnoremap H move_cursor_left
gnnoremap L move_cursor_right
gnnoremap K move_cursor_up
gnnoremap J move_cursor_down
gnnoremap <C-g> jump_cursor_to_top
gnnoremap <C-G> jump_cursor_to_bottom
gnnoremap <C-m> jump_cursor_to_hcenter
gnnoremap <C-M> jump_cursor_to_vcenter
gnnoremap k scroll_up
gnnoremap j scroll_down
gnnoremap s scroll_up_halfpage
gnnoremap d scroll_down_halfpage
gnnoremap gg scroll_up_onepage
gnnoremap G scroll_down_onepage
gnnoremap f easy_click_left
gnnoremap N goto_next_page
gnnoremap C goto_prev_page
gnnoremap h switch_to_left_tab
gnnoremap l switch_to_right_tab
gnmap <Capslock> <ctrl>



gvnoremap K scroll_up
gvnoremap J scroll_down
gvmap <Capslock> <Esc>  
gvnoremap gh switch_to_left_tab
gvnoremap gl switch_to_right_tab
gvnoremap <Esc> to_gui_normal


evnoremap <Esc> to_edi_normal
evmap <Capslock> <Esc> 


command tp switch_to_left_tab
command tn switch_to_right_tab
command tt open_new_tab


inoremap <c-[> to_edi_normal

```

Apparently the issue occurs when the text field can lose focus, like by pressing `esc`. It doesn't happen in desktop apps like notepad.

Thanks

**Comment by pit-ray** [comment]
Thanks for the quick reply! I'll try it.

**Comment by pit-ray** [comment]
Thanks to your report, I found some bugs in the parser of .vindrc. As soon as fixed, I will give you its build binary. However, I still don't know the cause of the loss of focus, as I could not reproduce. Hopefully, this fix will solve it indirectly.

Thanks

**Comment by pit-ray** [comment]
Hi.

I fixed some bugs in the .vindrc parser. You can download the build directly from [here](https://github.com/pit-ray/win-vind/files/6825744/win-vind_4.0.1_issue_26_1_64bit.zip), and its code is [here](
https://github.com/pit-ray/win-vind/tree/275977050a5da99317c3e8551014e8395c83a2f3).

If does not solve the problem, I will add an option to autofocus the appropriate text filed near the mouse cursor in `to_edi_normal`.

Thanks.

**Comment by Positron010** [comment]
Hi, 
Thanks for your effort.
Unfortunately, the issue still persists with this build. I used the default .vindrc, just changed the shortcut for transitioning to `edi_normal` to avoid pressing `esc`, but that didn't solve the issue.

Thanks

**Comment by pit-ray** [comment]
Thanks for trying.
Now, I'm implementing the new option to solve this problem.  Please wait for a while.

**Comment by Positron010** [comment]
Hi,
Thanks for your efforts and take your time. Appreciate it.

**Comment by Positron010** [comment]
Hi, just a quick update.

I just found out that this issue resolves when changing the hotkey to something that is written in the input field. For example, I don't face the issue when I make the `to_edi_normal` from insert mode to be `jj`. It just transitions to it. You can then undo these two letters to get a somehow working solution. 
Hope this helps.

Thanks

**Comment by Positron010** [comment]
Well, this is embarrassing 😅. It was apparently the shortcut causing the issue. I also just changed my shortcut to something not typed like <kbd>ctrl-/</kbd> and now it works without losing focus. Sorry for that, and thanks again for your efforts. I believe the default shortcut might need changing because <kbd>esc</kbd> causes many input fields to lose focus. 

Thanks again, and I am sorry for consuming your time. Feel free to close the issue if you like.

**Comment by pit-ray** [comment]
Even little things can be helpful for development.

A feature to prevent losing focus is implementable. I'm sure some users would be helped by this option.
I keep the issue open until implementation is completed.

**Comment by Positron010** [comment]
Yes, I agree with that. It would be better to have such an option.
All the best.

**Comment by Positron010** [comment]
Hi,
I just tested it, and it works really great! The only area of improvement I can see is increasing the speed of the process, but that is negligible. Thanks for your efforts!

**Comment by pit-ray** [comment]
Today, I released [v4.1](https://github.com/pit-ray/win-vind/releases/tag/v4.1.0) and it includes the new option `uiacachebuild`. If enable this option, `autofocus_textarea` and EasyClick become very faster. However, depending on the value of `uiacachebuild_lifetime`, the accuracy may decrease.

**Comment by Positron010** [comment]
Hi,
Thanks as always. Keep up the good work.
